# Get base SDK Image from Microsoft
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.101 AS build
WORKDIR /app

# Copy the csproj files and restore any dependencies (via Nuget)
COPY *.csproj ./
RUN dotnet restore

# Copy the project files and build our release
COPY . ./
RUN dotnet publish -c Release -o out

# Generate runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
EXPOSE 5000
EXPOSE 5001
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "StudentMgtAPI.dll"]
